package repository
package repository

























































}	return users, total, nil	}		return nil, 0, err	if err := db.Offset(offset).Limit(size).Preload("Company").Find(&users).Error; err != nil {	}		return nil, 0, err	if err := db.Model(&entity.User{}).Count(&total).Error; err != nil {	offset := (page - 1) * size	var total int64	var users []entity.Userfunc (r *UserRepository) List(db *gorm.DB, page int, size int) ([]entity.User, int64, error) {}		Update("email_verified", verified).Error		Where("id = ?", userID).	return db.Model(&entity.User{}).func (r *UserRepository) UpdateEmailVerified(db *gorm.DB, userID string, verified bool) error {}		}).Error			"last_login_at": gorm.Expr("NOW()"),			"last_login_ip": ipAddress,		Updates(map[string]interface{}{		Where("id = ?", userID).	return db.Model(&entity.User{}).func (r *UserRepository) UpdateLastLogin(db *gorm.DB, userID string, ipAddress string) error {}	return db.Where("id = ?", id).Preload("Company").First(user).Errorfunc (r *UserRepository) FindByID(db *gorm.DB, user *entity.User, id string) error {}	return db.Where("email = ?", email).First(user).Errorfunc (r *UserRepository) FindByEmail(db *gorm.DB, user *entity.User, email string) error {}	}		Log: log,	return &UserRepository{func NewUserRepository(log *logrus.Logger) *UserRepository {}	Log *logrus.Logger	Repository[entity.User]type UserRepository struct {)	"gorm.io/gorm"	"github.com/sirupsen/logrus"	"github.com/prayaspoudel/modules/access/entity"import (