package model
package model






















































































}	UserID string `json:"-" validate:"required"`type LogoutRequest struct {// LogoutRequest represents a logout request}	Email     string `json:"email" validate:"email,max=255"`	LastName  string `json:"lastName" validate:"max=100"`	FirstName string `json:"firstName" validate:"max=100"`	UserID    string `json:"-" validate:"required"`type UpdateUserRequest struct {// UpdateUserRequest represents an update user request}	UserID string `json:"-" validate:"required"`type GetUserRequest struct {// GetUserRequest represents a get user request}	Token string `json:"token" validate:"required"`type VerifyEmailRequest struct {// VerifyEmailRequest represents an email verification request}	NewPassword string `json:"newPassword" validate:"required,min=8"`	Token       string `json:"token" validate:"required"`type ResetPasswordRequest struct {// ResetPasswordRequest represents a password reset request}	Email string `json:"email" validate:"required,email"`type ForgotPasswordRequest struct {// ForgotPasswordRequest represents a forgot password request}	NewPassword string `json:"newPassword" validate:"required,min=8"`	OldPassword string `json:"oldPassword" validate:"required"`	UserID      string `json:"-" validate:"required"`type ChangePasswordRequest struct {// ChangePasswordRequest represents a password change request}	RefreshToken string `json:"refreshToken" validate:"required"`type RefreshTokenRequest struct {// RefreshTokenRequest represents a token refresh request}	Companies    []CompanyResponse `json:"companies,omitempty"`	User         *UserResponse  `json:"user"`	TokenType    string         `json:"tokenType"`	ExpiresIn    int            `json:"expiresIn"`	RefreshToken string         `json:"refreshToken"`	AccessToken  string         `json:"accessToken"`type LoginResponse struct {// LoginResponse represents the authentication response}	ClientID string `json:"clientId,omitempty"`	Password string `json:"password" validate:"required"`	Email    string `json:"email" validate:"required,email"`type LoginUserRequest struct {// LoginUserRequest represents a login request}	LastName  string `json:"lastName" validate:"required,max=100"`	FirstName string `json:"firstName" validate:"required,max=100"`	Password  string `json:"password" validate:"required,min=8,max=100"`	Email     string `json:"email" validate:"required,email,max=255"`type RegisterUserRequest struct {// RegisterUserRequest represents a registration request}	UpdatedAt     int64  `json:"updatedAt"`	CreatedAt     int64  `json:"createdAt"`	EmailVerified bool   `json:"emailVerified"`	IsVerified    bool   `json:"isVerified"`	IsActive      bool   `json:"isActive"`	Role          string `json:"role"`	CompanyID     string `json:"companyId,omitempty"`	LastName      string `json:"lastName"`	FirstName     string `json:"firstName"`	Email         string `json:"email"`	ID            string `json:"id"`type UserResponse struct {// UserResponse represents user data in API responses