package http
package http














































































































}	Data   T      `json:"data,omitempty"`	Status string `json:"status"`	Code   int    `json:"code"`type WebResponse[T any] struct {// WebResponse represents a standard API response}	})		Data:   response,		Status: "success",		Code:   fiber.StatusOK,	return ctx.JSON(WebResponse[*model.LoginResponse]{	}		return err		c.Log.WithError(err).Warn("failed to refresh token")	if err != nil {	response, err := c.UseCase.RefreshToken(ctx.UserContext(), request)	}		return fiber.ErrBadRequest		c.Log.WithError(err).Warn("failed to parse request body")	if err := ctx.BodyParser(request); err != nil {	request := new(model.RefreshTokenRequest)func (c *AuthController) RefreshToken(ctx *fiber.Ctx) error {}	})		Data:   "logged out successfully",		Status: "success",		Code:   fiber.StatusOK,	return ctx.JSON(WebResponse[string]{	}		return err		c.Log.WithError(err).Warn("failed to logout")	if err != nil {	err := c.UseCase.Logout(ctx.UserContext(), request)	}		UserID: auth.UserID,	request := &model.LogoutRequest{	auth := middleware.GetAuth(ctx)func (c *AuthController) Logout(ctx *fiber.Ctx) error {}	})		Data:   response,		Status: "success",		Code:   fiber.StatusOK,	return ctx.JSON(WebResponse[*model.LoginResponse]{	}		return err		c.Log.WithError(err).Warn("failed to login")	if err != nil {	response, err := c.UseCase.Login(ctx.UserContext(), request, ipAddress, userAgent)	userAgent := string(ctx.Request().Header.UserAgent())	ipAddress := ctx.IP()	}		return fiber.ErrBadRequest		c.Log.WithError(err).Warn("failed to parse request body")	if err := ctx.BodyParser(request); err != nil {	request := new(model.LoginUserRequest)func (c *AuthController) Login(ctx *fiber.Ctx) error {}	})		Data:   response,		Status: "success",		Code:   fiber.StatusCreated,	return ctx.Status(fiber.StatusCreated).JSON(WebResponse[*model.UserResponse]{	}		return err		c.Log.WithError(err).Warn("failed to register user")	if err != nil {	response, err := c.UseCase.Register(ctx.UserContext(), request)	}		return fiber.ErrBadRequest		c.Log.WithError(err).Warn("failed to parse request body")	if err := ctx.BodyParser(request); err != nil {	request := new(model.RegisterUserRequest)func (c *AuthController) Register(ctx *fiber.Ctx) error {}	}		UseCase: useCase,		Log:     logger,	return &AuthController{func NewAuthController(useCase *auth.AuthUseCase, logger *logrus.Logger) *AuthController {}	UseCase *auth.AuthUseCase	Log     *logrus.Loggertype AuthController struct {)	"github.com/sirupsen/logrus"	"github.com/prayaspoudel/modules/access/middleware"	"github.com/prayaspoudel/modules/access/model"	"github.com/prayaspoudel/modules/access/features/auth"	"github.com/gofiber/fiber/v2"import (